name: Continuous deployment

# On push events to the main branch
on:
  push:
    branches:
      - main

# Steps are done on ubuntu virtual machine
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #Get our source code into the VM
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hizackdavid/postgresql-container:latest
          # run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
