name: Continuous deployment

# On push events to the main branch
on:
  push:
    branches:
      - main

# Steps are done on ubuntu virtual machine
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #Get our source code into the VM
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hizackdavid/postgresql-container:latest
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        uses: docker/login-action@v2.2.0
        with:
          # Username used to log against the Docker registry
          username: ${{ DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ DOCKERHUB_PASSWORD }}
